apiVersion: v1
kind: Service
metadata:
  name: portal-console
spec:
  ports:
    - port: 8080
  selector:
    tier: portal-console
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-console
spec:
  selector:
    matchLabels:
      tier: portal-console
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: portal-console
    spec:
      containers:
      - image: eugeniosant/portal-console:7.2.2.0-rc1
        name: portal-console
        imagePullPolicy: IfNotPresent
        env:
        - name: KEYCLOAK_ENABLED
          value: 'true'
        - name: KEYCLOAK_REALM
          value: entando
        - name: KEYCLOAK_PUBLIC_CLIENT_ID
          value: entando-web-admin-console
        - name: KEYCLOAK_AUTH_URL
          value: 'https://test-en7.k8s-entando.org/auth'
        - name: KEYCLOAK_CLIENT_ID
          value: test-en7-portal-console
        - name: KEYCLOAK_CLIENT_SECRET
          value: trWeaWPbtpUQvb1ssOzSYnCdDRmX8aQ0
        - name: ENTANDO_RB_CONFIG_ON_FILE
          value: 'false'
        - name: ENTANDO_RB_CONSUMER_ENTANDO7_CORE_LIB_ACTIVE
          value: 'true'
        - name: ENTANDO_RB_CONSUMER_ENTANDO7_PORTAL_LIB_ACTIVE
          value: 'true'
        - name: ENTANDO_RB_CONSUMER_ENTANDO7_PLUGIN_CMS_LIB_ACTIVE
          value: 'true'
        - name: ENTANDO_RB_CONSUMER_ENTANDO7_CORE_LIB_DEFAULT_GRPC_HOST_PORT
          value:  test-en7-grpc-service:8088
        - name: ENTANDO_RB_CONSUMER_ENTANDO7_PORTAL_LIB_DEFAULT_GRPC_HOST_PORT
          value:  test-en7-grpc-service:8088
        - name: ENTANDO_RB_CONSUMER_ENTANDO7_PLUGIN_CMS_LIB_DEFAULT_GRPC_HOST_PORT
          value:  test-en7-grpc-service:8088
        - name: REDIS_ACTIVE
          value: "true"
        - name: REDIS_SESSION_ACTIVE
          value: "true"
        - name: REDIS_ADDRESS
          value: redis://redis:6379
        - name: SLAVE_INSTANCE_ID
          value: portal-console
        - name: APPBUILDERINTEGRATIONENABLED                                                                                                           
          value: "false"
        ports:
        - containerPort: 8080
          name: portal-console
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: quickstart-portal-console-ingress
spec:
  rules:
  - host: 10-219-168-145.nip.io
    http:
      paths:
      - backend:
              service:
                name: portal-console
                port:
                  number: 8080
        path: /portal-console
        pathType: Prefix
